
from scripts.csv_columns import *

ROW_INDEX = 'ID'

# Database Tables
LISTING = 'Listing'
PROPERTY = 'Property'
EXCHANGE_RATE = "Exchange Rate"

PROPERTY_AMENITIES = f'{PROPERTY}_{AMENITIES}'
PROPERTY_APPLIANCES = f'{PROPERTY}_{APPLIANCES}'
PROPERTY_PARKING = f'{PROPERTY}_{PARKING}'

TABLES = [
    PROVINCE,
    ADMINISTRATIVE_UNIT, 
    TOWN, 
    ADDRESS, 
    AMENITIES,
    APPLIANCES,
    PARKING,
    RENOVATION,
    CONSTRUCTION,
    CURRENCY,
    EXCHANGE_RATE,
    LISTING,
    PROPERTY_AMENITIES,
    PROPERTY_APPLIANCES,
    PROPERTY_PARKING
]

LINKAGE_MAP = {
    AMENITIES: PROPERTY_AMENITIES,
    APPLIANCES: PROPERTY_APPLIANCES,
    PARKING: PROPERTY_PARKING
}

